services:
  influxdb:
    image: influxdb:2.7
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxDb:/var/lib/influxdb2
  grafana:
    image: grafana/grafana
    restart: always
    depends_on:
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
volumes:
  influxDb: {}
  grafana: {}