{
 "title": "CSI",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Received packets per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"csi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"packet_rate\")\n  |> filter(fn: (r) => r[\"_field\"] == \"rate\")\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Connected nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"csi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"csi\" and r.source != \"34:85:18:b9:1a:81\")\n  |> map(fn: (r) => ({_value: r.source}))\n  |> distinct()\n  |> count()\n  |> yield(name: \"connected_stations\")"
    }
   ]
  },
  {
   "title": "Downlink phases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"csi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"csi\" and r[\"_field\"] == \"phase\" and r[\"destination\"] != \"34:85:18:b9:1a:81\" and r._value != 0)\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, subcarrier: r.subcarrier}))\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: false)\n  |> yield(name: \"downlink_phases\")"
    }
   ]
  },
  {
   "title": "Downlink amplitudes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"csi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"csi\" and r[\"_field\"] == \"amplitude\" and r[\"destination\"] != \"34:85:18:b9:1a:81\" and r._value != 0)\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, subcarrier: r.subcarrier}))\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: false)\n  |> yield(name: \"downlink_amplitudes\")"
    }
   ]
  },
  {
   "title": "UDP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"csi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"udp\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packet receive errors\" or r[\"_field\"] == \"receive buffer errors\")\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: false)\n  |> yield(name: \"errors\")"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"csi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"csi\" and r.destination != \"34:85:18:b9:1a:81\")\n  |> map(fn: (r) => ({_value: int(v: r.rssi), _time: r._time}))\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: false)\n  |> yield(name: \"downlink\")"
    },
    {
     "query": "from(bucket: \"csi\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"csi\" and r.destination == \"34:85:18:b9:1a:81\")\n  |> map(fn: (r) => ({_value: int(v: r.rssi), _time: r._time}))\n  |> aggregateWindow(every: 60s, fn: mean, createEmpty: false)\n  |> yield(name: \"uplink\")"
    }
   ]
  },
  {
   "title": "InfluxDB disk size rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "rate(storage_shard_disk_size{job=\"influxdb\", id=\"5\"}[1m]) / 1000000",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}